### ISSUE TITLE
Section Reference to section

### ISSUE THREAD

**Issue by duyhoang-astro** [o-smirnov/dan-price-coherency-paper#2]
Hi. I am using this LyX MNRAS layout to prepare a manuscript. One issue I have is that reference to a section seems not to work. It works on other labels such as subsections, figures, tables, equations, etc. But not with section labels. I am wondering if you have seen this issue and know how to fix it? Thanks!

**Comment by Vital-Fernandez** [comment]
I have the same issue. How did you solve it?

**Comment by telegraphic** [comment]
Hey both,

Not sure if I will be able to fix this, but let's move the conversation over to this dedicated repository:
https://github.com/telegraphic/mn2e-lyx/issues/1
