### ISSUE TITLE
Position placements printed on pdf

### ISSUE THREAD

**Issue by Vital-Fernandez** [o-smirnov/dan-price-coherency-paper#3]
First of all I want to thank you for this. 

I have an issue : The position placement are included on pdf ([h]) for example. How did you avoid this in your example paper?

**Comment by telegraphic** [comment]
Hi @Delosari, I didn't realize anyone was using the lyx template from this repository. Can we move discussion to the newly-created https://github.com/telegraphic/mn2e-lyx?
